services:
    upptime-embed:
        image: upptime-embed
        container_name: upptime-embed
        build:
            context: .
            dockerfile: Dockerfile
        pull_policy: never
        ports:
            - 3001:3001
        user: 1000:1000
        restart: unless-stopped
